version: 2.1
jobs:
  # install and testing task
  build:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      
  # Deploy with Surge task
  deploy:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: npm install --save-dev surge
      - run: npm run build #build static html file
      # --project path/to/your-pj --domain your-url.surge.sh
      - run: ./node_modules/surge/lib/cli.js --project ./build --domain bozuman-usdtovnd.surge.sh
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build
      # - run: actions/checkout@v2 ./node_modules/surge/lib/cli.js
      # - run: npm ci
      # - run: |
      #     npm link
      #     npm link @jsdevtools/eslint-config-modular
      # - run: npm run lint


      
