version: 2.1
jobs:
  # build task
  build:
    docker:
      - image: circleci/node:16.15.1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  # Deploy with Surge task
  deploy:
    docker:
      - image: circleci/node:16.15.1
    steps:
      - checkout
      - run: npm install --save-dev surge
      - run: ./node_modules/surge/lib/cli.js --project ./ --domain bozuman-usdtovnd.surge.sh
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build