version: 2.1

jobs:
  # install and testing task
  build:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout 
      - run: npm install
      - run: npm run test


  eslint:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint -- --fix



  # Deploy with Surge task
  deploy:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm install --save-dev surge
      - run: ./node_modules/surge/lib/cli.js --project ./ --domain bozuman-usdtovnd.surge.sh


workflows:
  build-and-deploy:
    jobs:
      - build
      - eslint:
          requires:
              - build
      - deploy:
          requires:
              - eslint


      
