version: 2.1

jobs:
  # build task
  build:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout 
      - run: npm install
      - run: npm run test


  eslint:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: npm run eslint


  # Deploy with Surge task
  deploy:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: npm install --save-dev surge
      - run: ./node_modules/surge/lib/cli.js --project ./ --domain bozuman-usdtovnd.surge.sh


workflows:
  build-and-deploy:
    jobs:
      - build
      - eslint:
          requires:
              - build
      - deploy:
          requires:
              - eslint









              
      # - run: actions/checkout@v2
      # - run: npm ci
      # - run: |
      #     npm link
      #     npm link @jsdevtools/eslint-config-modular
      # - run: npm run lint


      
